module.exports = function($translateProvider) {
    $translateProvider.translations('he', {
        'Killer': 'רוצח במילה',
        'Talk yourself out of it':'משחק חברתי משעשע',
        'Prepare a Game for':'הכן משחק ל',
        'players':'שחקנים',
        'minimum three players':'מינימום שלושה שחקנים',
        'Continue':'המשך',
        'instructions':'הוראות',
        'The game is for a group of people (at least 3) that are together.':'המשחק מיועד לקבוצת אנשים, 3 ומעלה, שנמצאים יחד.',
        'Each player gets a mission:':'כל שחקן מקבל משימה: ',
        'a name of another player (the victim) that he needs to eliminate and a secret word.':'שם של שחקן אחר (הקורבן) שהוא צריך להרוג ומילה באמצעותה יתבצע הרצח.',
        'The killer will need to make his victim say the secret word.':'המטרה של השחקן היא לגרום לקורבן להגיד את מילת הרצח (השחקן צריך לשמוע את הקורבן אומר את המילה).',
        'A player that was killed, is out of the game and his mission goes to his killer.':'קורבן שנרצח יוצא מהמשחק והמשימה שלו עוברת לרוצחו',
        'Last man standing is the winner!':'מי שנשאר אחרון הוא המנצח!',
        'Add the players:':'הוסף שחקנים:',
        'Player Name:':'שם שחקן:',
        'Add player':'הוסף שחקן',
        'Killers-Chain is Ready!':'המשחק מוכן!',
        'I will now call each player in a random order and reveal his task.':'כעת אקרא לשחקנים, בסדר רנדומלי ואגלה לכל אחד באופן אישי את המשימה שלו...',
        'OK, Do it!':'אוקיי, המשך',
        'Go Back':'חזור אחורה',
        'Revealing Tasks':'חלוקת משימות',
        'I’m Here!':'אני כאן',
        'Your task is to kill':'המשימה שלך היא להרוג את',
        'With the word':'עם המילה',
        'Got it!':'קיבלתי!',
        'I did it!':'המשימה בוצעה!',
        'Done Revealing Tasks':'חלוקת המשימות הסתיימה',
        'Game in progress.':'המשחק התחיל!',
        'Restart':'משחק חדש',
        'New Game':'משחק חדש',
        'Existing players':'אותם שחקנים',
        'Are you':'האם אתה',
        'Yes I swear I am!':'כן, זה אני!',
        'No, sorry about that':'לא, מצטער',
        'Game Over':'המשחק נגמר',
        'you are the Winner!':'אתה המנצח!',
        'Play again with the same players':'שחק שוב עם אותם שחקנים'
    });
}